server:
  port: 9090

spring:
  profiles:
    active: BLACKBOARDING
    
---
# 1.1 directly architectural style
spring:
  profiles: CLOUD 
  
security:
  oauth2:
    resource:
      # endpoint of the authorization server for token check
      token-infouri: http://localhost:8080/oauth/check_token
    client:
      # credentials of this resource server for authentication server
      client-id: resourceserver1
      client-secret: resourceserversecret1
  
---
# 1.2 directly architectural style
spring:
  profiles: INTROSPECTION 
 
---
# 2. blackboarding architectural style
spring:
  profiles: BLACKBOARDING 

  datasource:
    url: jdbc:mysql://localhost/blackboarding
    username: root
    password: root

